[workspace]

[package]
name = "exploit"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "3.0.4", default-features = false, features = ["std"] }
bridge-types = { path = "../../core/bridge-types" }
bridge-logic = { path = "../../core/bridge-logic", default-features = false }
rkyv = { version = "0.7.45", features = ["validation", "std", "size_32"] }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
serde = { version = "1", features = ["derive"] }
alloy-primitives = { version = "0.8", default-features = false, features = ["std"] }
revm = { version = "19", default-features = false, features = ["std"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
